### ISSUE TITLE
CircleCI builds broken?

### ISSUE THREAD

**Issue by jotaen4tinypilot** [tiny-pilot/ansible-role-nginx#4]
It appears that the build is broken on master: https://app.circleci.com/pipelines/github/tiny-pilot/ansible-role-nginx/18/workflows/0c69b125-02fc-4e69-aa0f-d4abc212e673

This happens in the “Checkout Code” phase, so potentially just a configuration problem? (I couldn’t spot anything immediately obvious in the [workflow file](https://github.com/tiny-pilot/ansible-role-nginx/blob/master/.circleci/config.yml).)

**Comment by mtlynch** [comment]
Looks like CircleCI invalidated all their SSH keys due to the breach. Good thing, because I didn't think to do that this morning (although it just gives read-only access to our code, which isn't that interesting).

Fixed now: https://app.circleci.com/pipelines/github/tiny-pilot/ansible-role-nginx/19/workflows/39b3c267-967e-4ecf-ade3-f4c0b3bc3695
